version: "3.8"

services:
  # nest:
  #   container_name: nest
  #   build: .
  #   command: yarn start:dev
  #   volumes:
  #     - .:/app
  # - node_modules:/app/node_modules
  # - /app/node_modules

  shhareit-mongo:
    volumes:
      - ./mongodb_dev:/data/db
    ports: # expose port outside docker
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: dev
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    # networks:
    #   - internal

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: shhareit-mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
  # networks:
  #   - internal
volumes:
  node_modules:
# networks:
#   internal:
#     driver: bridge
