version: "3.8"

services:
  nest:
    container_name: nest
    build:
      context: .
      target: staging
    command: yarn start:stag
    ports:
      - 3000:3000

  shhareit-mongo:
    container_name: mongodb_staging
    image: mongo:latest
    expose: # expose port only internal for docker
      - 27017
    volumes:
      - ./mongodb/staging:/data/db
    environment:
      MONGO_INITDB_DATABASE: staging
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: shhareit-mongo
      ME_CONFIG_BASICAUTH_USERNAME: xadmin
      ME_CONFIG_BASICAUTH_PASSWORD: adminx
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
